package com.kivkung.universalclipboard;
import android.content.*;import android.database.*;import android.net.Uri;import android.os.*;import android.provider.OpenableColumns;import java.io.*;import org.json.*;
/** Read-only local payloads, including exact display name, MIME and size. */
public final class HistoryProvider extends ContentProvider {
 public boolean onCreate(){return true;}
 private String[] parse(Uri u)throws FileNotFoundException{String p=u.getPath();if(!getContext().getPackageName().concat(".history").equals(u.getAuthority())||p==null||!p.matches("/[a-f0-9]{64}/[0-9]{1,2}"))throw new FileNotFoundException("Invalid history URI");return p.substring(1).split("/");}
 public String getType(Uri u){try{String[] p=parse(u);return new HistoryStore(getContext()).item(p[0],Integer.parseInt(p[1])).getString("mime");}catch(Exception e){return null;}}
 public Cursor query(Uri u,String[] projection,String selection,String[] args,String order){try{String[] p=parse(u);HistoryStore s=new HistoryStore(getContext());JSONObject f=s.item(p[0],Integer.parseInt(p[1]));String[] cols=projection==null?new String[]{OpenableColumns.DISPLAY_NAME,OpenableColumns.SIZE}:projection;MatrixCursor cursor=new MatrixCursor(cols);Object[] row=new Object[cols.length];for(int i=0;i<cols.length;i++)row[i]=OpenableColumns.DISPLAY_NAME.equals(cols[i])?f.getString("name"):OpenableColumns.SIZE.equals(cols[i])?f.getLong("size"):null;cursor.addRow(row);return cursor;}catch(Exception e){return null;}}
 public ParcelFileDescriptor openFile(Uri u,String mode)throws FileNotFoundException{if(!"r".equals(mode))throw new FileNotFoundException("Read only");try{String[] p=parse(u);HistoryStore s=new HistoryStore(getContext());s.lease(p[0]);synchronized(HistoryStore.LOCK){HistoryStore.READERS.put(p[0],HistoryStore.READERS.getOrDefault(p[0],0)+1);try{return ParcelFileDescriptor.open(s.payload(p[0],Integer.parseInt(p[1])),ParcelFileDescriptor.MODE_READ_ONLY,new Handler(Looper.getMainLooper()),error->{synchronized(HistoryStore.LOCK){HistoryStore.READERS.put(p[0],Math.max(0,HistoryStore.READERS.getOrDefault(p[0],0)-1));s.cleanup();}});}catch(Exception e){HistoryStore.READERS.put(p[0],Math.max(0,HistoryStore.READERS.getOrDefault(p[0],0)-1));throw e;}}}catch(Exception e){throw new FileNotFoundException(e.getMessage());}}
 public Uri insert(Uri u,ContentValues v){throw new UnsupportedOperationException("Read only");}public int update(Uri u,ContentValues v,String s,String[] a){throw new UnsupportedOperationException("Read only");}public int delete(Uri u,String s,String[] a){throw new UnsupportedOperationException("Read only");}
}
