package com.kivkung.universalclipboard;
import android.app.*;import android.content.*;import android.net.Uri;import android.os.*;import android.widget.*;import java.util.*;import org.json.*;
/** Five latest successful entries; permanent exports never belong to the temporary cache. */
public final class HistoryActivity extends Activity {
 static Intent action(Context c,String id,String verb){return new Intent(c,HistoryActivity.class).putExtra("id",id).putExtra("action",verb).setData(Uri.parse("uc-history:"+id+":"+verb));}
 static void notifyReceived(Context c,String id){NotificationManager nm=c.getSystemService(NotificationManager.class);nm.createNotificationChannel(new NotificationChannel("received","Received clipboard files",NotificationManager.IMPORTANCE_DEFAULT));Notification.Builder b=new Notification.Builder(c,"received").setSmallIcon(R.drawable.ic_status).setContentTitle("Files received").setContentText("Open, share, or save permanently to Downloads").setAutoCancel(true).setContentIntent(PendingIntent.getActivity(c,40,new Intent(c,HistoryActivity.class),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE));int code=41;for(String verb:new String[]{"Open","Share","Save"})b.addAction(new Notification.Action.Builder(null,verb,PendingIntent.getActivity(c,code++,action(c,id,verb),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE)).build());nm.notify(2,b.build());}
 @Override public void onCreate(Bundle saved){super.onCreate(saved);render();String id=getIntent().getStringExtra("id"),a=getIntent().getStringExtra("action");if(id!=null&&a!=null)perform(id,a);}
 void render(){LinearLayout box=new LinearLayout(this);box.setOrientation(1);int p=(int)(16*getResources().getDisplayMetrics().density);box.setPadding(p,p,p,p);ScrollView scroll=new ScrollView(this);scroll.addView(box);TextView heading=new TextView(this);heading.setText("Clipboard history · latest 5");heading.setTextSize(23);box.addView(heading);HistoryStore s=new HistoryStore(this);TextView note=new TextView(this);note.setText("Temporary history, partials and pinned files share the budget. Save keeps a permanent copy in Downloads. Shared files remain readable for at least 24 hours.");box.addView(note);Button budget=new Button(this);budget.setText("Storage budget: "+(Config.prefs(this).getLong("historyBudgetBytes",HistoryStore.DEFAULT_BUDGET)/(1024*1024))+" MiB");box.addView(budget);budget.setOnClickListener(v->{EditText field=new EditText(this);field.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);field.setText("1024");new AlertDialog.Builder(this).setTitle("Budget in MiB (256–65536)").setView(field).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{try{long n=Long.parseLong(field.getText().toString());if(n<256||n>65536)throw new Exception();Config.prefs(this).edit().putLong("historyBudgetBytes",n*1024*1024).commit();render();}catch(Exception e){Toast.makeText(this,"Enter 256–65536 MiB",Toast.LENGTH_LONG).show();}}).show();});
 for(JSONObject e:s.list())try{String id=e.getString("id");TextView title=new TextView(this);JSONArray fs=e.getJSONArray("files");String label=e.getString("kind").equals("text")?e.getString("text"):fs.length()+" file(s): "+fs.getJSONObject(0).getString("name");title.setText(label+"\n"+new java.util.Date(e.getLong("timestamp"))+" · "+e.optString("sender"));title.setTextSize(17);title.setPadding(0,p,0,0);box.addView(title);LinearLayout actions=new LinearLayout(this);box.addView(actions);for(String verb:new String[]{"Copy","Open","Share","Save"}){Button b=new Button(this);b.setText(verb);b.setAllCaps(false);actions.addView(b,new LinearLayout.LayoutParams(0,-2,1));b.setOnClickListener(v->perform(id,verb));}}catch(Exception ignored){}setContentView(scroll);}
 void perform(String id,String verb){HistoryStore s=new HistoryStore(this);try{JSONObject e=s.get(id);boolean text="text".equals(e.getString("kind"));if(verb.equals("Copy")){s.copy(id);Toast.makeText(this,"Copied",Toast.LENGTH_SHORT).show();return;}if(verb.equals("Save")){new Thread(()->{try{s.save(id);runOnUiThread(()->Toast.makeText(this,"Saved to Downloads / Universal Clipboard",Toast.LENGTH_LONG).show());}catch(Exception ex){runOnUiThread(()->error(ex));}}).start();return;}if(text){Intent i=new Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT,e.getString("text"));startActivity(Intent.createChooser(i,"Share text"));return;}JSONArray fs=e.getJSONArray("files");s.lease(id);Intent i;if(verb.equals("Open")){if(fs.length()>1){String[] names=new String[fs.length()];for(int n=0;n<names.length;n++)names[n]=fs.getJSONObject(n).getString("name");new AlertDialog.Builder(this).setTitle("Open file").setItems(names,(d,w)->open(s,id,w)).show();return;}open(s,id,0);return;}ArrayList<Uri> uris=new ArrayList<>();for(int n=0;n<fs.length();n++)uris.add(s.uri(id,n));i=new Intent(fs.length()>1?Intent.ACTION_SEND_MULTIPLE:Intent.ACTION_SEND).setType(fs.length()>1?"*/*":fs.getJSONObject(0).getString("mime"));if(fs.length()>1)i.putParcelableArrayListExtra(Intent.EXTRA_STREAM,uris);else i.putExtra(Intent.EXTRA_STREAM,uris.get(0));ClipData clip=ClipData.newRawUri("History",uris.get(0));for(int n=1;n<uris.size();n++)clip.addItem(new ClipData.Item(uris.get(n)));i.setClipData(clip);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Share files"));}catch(Exception e){error(e);}}
 void open(HistoryStore s,String id,int index){try{Uri u=s.uri(id,index);Intent i=new Intent(Intent.ACTION_VIEW).setDataAndType(u,s.item(id,index).getString("mime"));i.setClipData(ClipData.newRawUri("History",u));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(i);}catch(Exception e){error(e);}}
 void error(Exception e){Toast.makeText(this,e.getMessage()==null?"No application available":e.getMessage(),Toast.LENGTH_LONG).show();}
}
